export const servidor = 'http://localhost:12611/api/';
export const listarEmpleado = servidor+'empleados/listar'
export const guardarEmpleado = servidor+'empleados/guardar'
export const editarEmpleado = servidor+'empleados/editar?id='
export const listarCargos = servidor+'cargos/listar'
export const guardarCargos = servidor+'cargos/guardar'
export const editarCargos = servidor+'cargos/editar?id='
export const listarClientes = servidor+'clientes/listar'
export const guardarClientes = servidor+'clientes/guardar'
export const editarClientes = servidor+'clientes/editar?id='
export const loginUsuarios = servidor+'autenticacion/iniciarsesion'
export const listarUsuarios = servidor+'usuarios/listar'
export const listarProfesiones = servidor+'profesiones/listar'
export const guardarProfesiones = servidor+'profesiones/guardar'
export const modificarProfesiones = servidor+'profesiones/editar?id='
export const imagenCliente = servidor + 'imagenes/clientes/'
export const imagenEmpleado = servidor + 'imagenes/empleados/'
export const imagenProyecto = servidor + 'imagenes/proyectos/'
export const clientesEditarImagen = 'clientes/editarimagen?id='
export const buscarIdClienteContrato = 'contratos/buscaridcliente?clienteId='
export const buscarIdClienteContratoPagoPendiente = 'contratos/buscaridclientepagopendiente?clienteId='
export const verAmortizacion = 'contratos/veramortizacion'
export const listarLugares = servidor + 'lugares/listar'
export const guardarLugares = 'lugares/guardar'
export const editarLugares = 'lugares/editar?id='
export const listarPaises = 'paises/listar'
export const listarDepartamentos = 'departamentos/listar'
export const guardarDepartamentos = 'departamentos/guardar'
export const editarDepartamentos = 'departamentos/editar?id='
export const listarMunicipios = 'municipios/listar'
export const guardarMunicipios= 'municipios/guardar'
export const editarMunicipios = 'municipios/editar?id='
export const buscarIpCaja = 'cajas/buscarip'
export const buscarIpEstacion = 'estaciones/buscarip'
export const guardarApertura = 'aperturas/guardar'
export const editarApertura = 'aperturas/editar?id='
export const listarAperturas = 'aperturas/listar'
export const buscarIdPago = 'pagos/buscarid?id='
export const listarPagos = 'pagos/listar'
export const guardarPagoCuotas = 'pagos/guardarpagocuotas'
export const guardarCierre = 'cierres/guardar'
export const datoCierre = 'cierres/datos?id='
export const datoIdApertura = servidor+'cierres/datosApertura?id='
export const editarCierre = 'cierres/editar?id='
export const listarCierres = 'cierres/listar'
export const listarAlquileres = 'alquiler/listar'
export const guardarAlquileres = 'alquiler/crear'
export const editarAlquileres = 'alquiler/editar?id='
export const listarProveedores = 'proveedor/listar'
export const guardarProveedores = 'proveedor/crear'
export const editarProveedores = 'proveedor/editar?id='
export const listarProductos = 'producto/listar'
export const guardarProductos = 'producto/crear'
export const editarProductos = 'producto/editar?id='
export const listarInventario = 'inventario/listar'
export const guardarInventario = 'inventario/crear'
export const editarInventario = 'inventario/editar?id='
export const listarNotaPeso = 'nota/listar'
export const guardarNotaPeso = 'nota/guardar'
export const editarNotaPeso = 'nota/editar?id='
export const listarDetalle = 'detalle/listar'
export const guardarDetalle = 'detalle/guardar'
export const editarDetalle = 'detalle/editar?id='
export const listarFactura = 'factura/listar'
export const guardarFactura = 'factura/guardar'
export const editarFactura = 'factura/editar?id='
export const listarTicket = 'ticket/listar'
export const guardarTicket = 'ticket/crear'
export const editarTicket = 'ticket/editar?id='


